### ISSUE TITLE
训练不了

### ISSUE THREAD

**Issue by XiaoZhang-NN** [HarukiYqM/Non-Local-Sparse-Attention#13]
python3.6.13,torch1.运行代码后出现

Making model...
Total params: 41.80M
Preparing loss function:
1.000 * L1
[Epoch 1]	Learning rate: 1.00e-4
Traceback (most recent call last):
  File "main.py", line 35, in <module>
    main()
  File "main.py", line 29, in main
    t.train()
  File "/home/zhangxiao/old-data/OISR-PyTorch-master/Non-Local-Sparse-Attention-main/trainer.py", line 42, in train
    for batch, (lr, hr, _,) in enumerate(self.loader_train):
  File "/home/zhangxiao/anaconda3/envs/fde3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "/home/zhangxiao/anaconda3/envs/fde3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
AttributeError: Traceback (most recent call last):
  File "/home/zhangxiao/anaconda3/envs/fde3/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/zhangxiao/anaconda3/envs/fde3/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/zhangxiao/anaconda3/envs/fde3/lib/python3.6/site-packages/torch/utils/data/dataset.py", line 85, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "/home/zhangxiao/old-data/OISR-PyTorch-master/Non-Local-Sparse-Attention-main/data/srdata.py", line 100, in __getitem__
    pair = self.get_patch(lr, hr)
  File "/home/zhangxiao/old-data/OISR-PyTorch-master/Non-Local-Sparse-Attention-main/data/srdata.py", line 143, in get_patch
    input_large=self.input_large
  File "/home/zhangxiao/old-data/OISR-PyTorch-master/Non-Local-Sparse-Attention-main/data/common.py", line 9, in get_patch
    ih, iw = args[0].shape[:2]
AttributeError: 'list' object has no attribute 'shape'

**Comment by HarukiYqM** [comment]
你好，你的gpu里有其他程序把显存占满了。NLSN可以在8G的显卡上训练。

**Comment by XiaoZhang-NN** [comment]
> 你好，你的gpu里有其他程序把显存占满了。NLSN可以在8G的显卡上训练。

谢谢您的回复。我用的是v100,训练用的是800张DIV2K测试用的是10张DIV2K，训练完后，紧接着用10张DIV2K测试时（用于选择最佳模型）显示内存不够了，请问这个原因是？您对数据进行了额外处理？

**Comment by HarukiYqM** [comment]
请在命令中加入—chop。这是一个sr中比较常用的方法将大图切成四块，用来减少测试时的显存占用。可以参考readme里的训练命令
python main.py --dir_data ../../ --n_GPUs 4 --rgb_range 1 --chunk_size 144 --n_hashes 4 --save_models --lr 1e-4 --decay 200-400-600-800 --epochs 1000 --chop --save_results --n_resblocks 32 --n_feats 256 --res_scale 0.1 --batch_size 16 --model NLSN --scale 2 --patch_size 96 --save NLSN_x2 --data_train DIV2K

**Comment by XiaoZhang-NN** [comment]
> 需要训练命令中加入—chop。这是一个sr中比较常用的方法(例如RCAN/SAN/CSNLN）将大图切成四块，用来缓解测试时的显存占用。可以参考readme里的训练命令
> python main.py --dir_data ../../ --n_GPUs 4 --rgb_range 1 --chunk_size 144 --n_hashes 4 --save_models --lr 1e-4 --decay 200-400-600-800 --epochs 1000 --chop --save_results --n_resblocks 32 --n_feats 256 --res_scale 0.1 --batch_size 16 --model NLSN --scale 2 --patch_size 96 --save NLSN_x2 --data_train DIV2K

特别感谢，麻烦您了，我试试看。

**Comment by cheun726** [comment]
> 你好，你的gpu里有其他程序把显存占满了。NLSN可以在8G的显卡上训练。

x3,x4的都可以在8G的卡上训练吗？为什么我x2的就不可以在11G的卡上训练？两张11G的可以，我看了一下内存占用大概是16G，并且没有其他程序占用显存。

**Comment by XiaoZhang-NN** [comment]
> > 你好，你的gpu里有其他程序把显存占满了。NLSN可以在8G的显卡上训练。
> 
> x3,x4的都可以在8G的卡上训练吗？为什么我x2的就不可以在11G的卡上训练？两张11G的可以，我看了一下内存占用大概是16G，并且没有其他程序占用显存。

您好，我是用的小模型--n_resblocks 8--n_feats 64 所以加上-chop之后就可以运行了。不知道是否符合您的问题。

**Comment by cheun726** [comment]
谢谢您，我用的32个residual blocks，减小了应该可以。
